import test from 'node:test';
import assert from 'node:assert/strict';
import {QUALITY_RULE_IDS, QUALIFICATION_WORKSTREAMS} from '../js/glaze-v1.3-qualification.candidate.mjs';
import {evaluateStableReadiness, STABLE_CLEANUP_WORKSTREAM, stableReadinessCandidate} from '../js/glaze-v1.3-stable-readiness.candidate.mjs';

const CANDIDATE='a'.repeat(40); const STABLE='b'.repeat(40); const AT='2026-09-07T02:30:00Z';
const MODES={'human-optical-and-icon-collision-qualification':'human','manual-assistive-technology-qualification':'human','physical-device-native-platform-qualification':'combined','physical-device-production-performance-qualification':'combined','native-personalization-adapter-qualification':'combined'};
function candidateRecord(id) { const value={schema_version:2,workstream_id:id,target:{product:'GLAZE UI V1.3',target_version:'1.3.0-candidate',source_revision:CANDIDATE},status:'passed',observed_at:'2026-09-07T02:00:00Z',valid_until:null,review_authority:{mode:MODES[id],authority:'authorized qualification review'},evidence_references:[`evidence/${id}/primary`,`evidence/${id}/review`],issues:[],disposition:{accepted_for_lifecycle_gate:true,notes:'fixture'}}; if(id===QUALIFICATION_WORKSTREAMS[0]) value.quality_review={contract:'contracts/v1.3/quality-rules.candidate.json',reviewed_rule_ids:[...QUALITY_RULE_IDS],visual_finish_accepted:true,blandness_rejected:true,accessibility_beauty_reviewed:true,responsive_beauty_reviewed:true,critical_final_quality_questions_accepted:true}; return value; }
function stableRecord(overrides={}) { const value={schema_version:2,workstream_id:STABLE_CLEANUP_WORKSTREAM,target:{product:'GLAZE UI V1.3',target_version:'1.3.0-candidate',source_revision:STABLE},status:'passed',observed_at:'2026-09-07T02:15:00Z',valid_until:null,review_authority:{mode:'combined',authority:'governed Stable readiness review'},environment:{qualified_candidate_source_revision:CANDIDATE,stable_promotion_source_revision:STABLE,candidate_lifecycle_observed:'active',equivalence_review_completed:true,import_closure_validated:true,rollback_verified:true},evidence_references:['evidence/stable-cleanup/equivalence','evidence/stable-cleanup/review'],issues:[],disposition:{accepted_for_lifecycle_gate:true,notes:'fixture'}}; return {...value,...overrides,target:{...value.target,...(overrides.target??{})},review_authority:{...value.review_authority,...(overrides.review_authority??{})},environment:{...value.environment,...(overrides.environment??{})},disposition:{...value.disposition,...(overrides.disposition??{})}}; }
function records(){ return [...QUALIFICATION_WORKSTREAMS.map(candidateRecord),stableRecord()]; }

test('Stable gate remains blocked while Candidate lifecycle is inactive',()=>{ const result=evaluateStableReadiness(records(),{candidateSourceRevision:CANDIDATE,stableSourceRevision:STABLE,candidateActive:false,evaluatedAt:AT}); assert.equal(result.state,'blocked'); assert.match(result.blockers.join('\n'),/Candidate lifecycle is not active/); assert.equal(result.stablePromoted,false); });
test('five qualified Candidate requirements plus exact Stable cleanup can satisfy only Stable readiness',()=>{ const result=evaluateStableReadiness(records(),{candidateSourceRevision:CANDIDATE,stableSourceRevision:STABLE,candidateActive:true,evaluatedAt:AT}); assert.equal(result.state,'ready-for-governed-stable-promotion-review'); assert.equal(result.stableGateSatisfied,true); assert.equal(result.candidateAcceptedWorkstreamCount,5); assert.equal(result.stableAcceptedWorkstreamCount,1); assert.equal(result.satisfiedQualificationRequirementCount,6); assert.equal(result.lifecyclePromotionGranted,false); assert.equal(result.stablePromoted,false); assert.equal(result.consumerConformanceGranted,false); });
test('Stable cleanup must preserve qualified Candidate revision provenance',()=>{ const bad=stableRecord({environment:{qualified_candidate_source_revision:'c'.repeat(40)}}); const result=evaluateStableReadiness([...QUALIFICATION_WORKSTREAMS.map(candidateRecord),bad],{candidateSourceRevision:CANDIDATE,stableSourceRevision:STABLE,candidateActive:true,evaluatedAt:AT}); assert.equal(result.stableGateSatisfied,false); assert.match(result.blockers.join('\n'),/qualified Candidate source revision provenance mismatch/); });
test('Stable cleanup must target the exact later Stable-promotion revision',()=>{ const bad=stableRecord({target:{source_revision:'c'.repeat(40)}}); const result=evaluateStableReadiness([...QUALIFICATION_WORKSTREAMS.map(candidateRecord),bad],{candidateSourceRevision:CANDIDATE,stableSourceRevision:STABLE,candidateActive:true,evaluatedAt:AT}); assert.match(result.blockers.join('\n'),/exact Stable-promotion source revision/); });
test('Stable cleanup cannot replace a missing Candidate qualification track',()=>{ const value=records(); value.splice(1,1); const result=evaluateStableReadiness(value,{candidateSourceRevision:CANDIDATE,stableSourceRevision:STABLE,candidateActive:true,evaluatedAt:AT}); assert.equal(result.stableGateSatisfied,false); assert.equal(result.candidateAcceptedWorkstreamCount,4); assert.match(result.blockers.join('\n'),/Candidate qualification: manual-assistive-technology-qualification/); });
test('Stable cleanup requires completed equivalence, import closure and rollback review',()=>{ const bad=stableRecord({environment:{equivalence_review_completed:false,import_closure_validated:false,rollback_verified:false}}); const result=evaluateStableReadiness([...QUALIFICATION_WORKSTREAMS.map(candidateRecord),bad],{candidateSourceRevision:CANDIDATE,stableSourceRevision:STABLE,candidateActive:true,evaluatedAt:AT}); const blockers=result.blockers.join('\n'); assert.match(blockers,/equivalence review is incomplete/); assert.match(blockers,/import-closure validation is incomplete/); assert.match(blockers,/rollback verification is incomplete/); });
test('Stable readiness metadata remains non-authoritative',()=>{ assert.equal(stableReadinessCandidate.stage,'post-candidate-pre-stable'); assert.equal(stableReadinessCandidate.requiresActiveCandidate,true); assert.equal(stableReadinessCandidate.candidateQualificationWorkstreamCount,5); assert.equal(stableReadinessCandidate.canPromoteStable,false); });
